config/routes.rb
Rails.application.routes.draw do

  resources :tools
  resources :users, only: [:new, :create, :show]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do
    resources :tools
  end
end

app/models/tool.rb
class Tool < ActiveRecord::Base

  validates :name, presence: true
  belongs_to :user
  
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password
  has_many :tools
  validates :username, presence: true, uniqueness: true
  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController

  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/tools_controller.rb
class Admin::ToolsController < Admin::BaseController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  def index
    @tools = Tool.all
    session[:most_recent_tool_id] = Tool.all.last.id
  end

  def show
    set_tool
  end

  def new
    @tool = Tool.new
    @users = User.all.map{|u| [ u.username, u.id ] }
  end

  def create
    @tool = Tool.new(tool_params)
    @user = User.find(params[:user_id])
    if @tool.save
      flash[:notice] = "Tool created."
      # @user.tools << @tool
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
    end
    redirect_to admin_tools_path #index
    # redirect_to tool_path(tool) #show
  end

  def edit
    set_tool
  end

  def update
    set_tool
    @tool.update(tool_params)
    redirect_to @tool
  end

  def destroy
    set_tool
    @tool.destroy
    redirect_to tools_path
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :use, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :most_recent_tool, :current_user

  def most_recent_tool
    @tool ||= Tool.find(session[:most_recent_tool_id]) if session[:most_recent_tool_id]
  end

  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:notice] = "Login successful."
      redirect_to @user
    end
  end

  def destroy
    session.clear
    redirect_to login_path
  end

end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController

  before_action :set_tool, only: [:show, :edit, :update, :destroy]

  def index
    @tools = Tool.all
    session[:most_recent_tool_id] = Tool.all.last.id
  end

  def show
    set_tool
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    # @user = User.find(session[:user_id])
    if @tool.save
      flash[:notice] = "Tool created."
      # @user.tools << @tool
    else
      flash[:error] = @tool.errors.full_messages.join(", ")
    end
    redirect_to tools_path #index
    # redirect_to tool_path(tool) #show
  end

  def edit
    set_tool
  end

  def update
    set_tool
    @tool.update(tool_params)
    redirect_to @tool
  end

  def destroy
    set_tool
    @tool.destroy
    redirect_to tools_path
  end

  private

  def set_tool
    @tool = Tool.find(params[:id])
  end

  def tool_params
    params.require(:tool).permit(:name, :use)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      flash[:notice] = "Account created."
      redirect_to user
    else
      flash.now[:error] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :use %>
  <%= f.text_field :use %>
  <%= f.label :user_id %>
  <%= f.text_field :user_id %>
  <%= f.submit %>
<% end %>

app/views/admin/tools/index.html.erb
<% flash.each do |type, msg| %>
  <h1><%= content_tag :div, msg, class: "flash_#{type}" %></h1>
<% end %>

<h1>Tools Index</h1>

<% @tools.each do |tool| %>
  <p><%= tool.name %>, use: (<%= tool.use %>)</p>
  <p><%= link_to "Edit", edit_tool_path(tool) %></p>
  <p><%= link_to "Delete", tool_path(tool), method: :delete %></p>
<% end %>

<%= link_to "New Tool", new_admin_tool_path %>

app/views/admin/tools/new.html.erb
<h1>New Tool</h1>

<%= render partial: "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <h1>Welcome, <%= current_user.username %></h1>
    <%= link_to "Logout", logout_path, method: :delete %>
  <% end %>

  <% flash.each do |type, message| %>
    <%= content_tag :div, message, class: "flash-#{type}" %>
  <% end %>
  <p><strong>Newest tool:</strong>
  <%= most_recent_tool.name if most_recent_tool %></p>
  <%= yield %>

</body>
</html>

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :use %>
  <%= f.text_field :use %>
  <%= f.submit %>
<% end %>

app/views/tools/edit.html.erb
<h1>Edit Tool</h1>

<%= render partial: "form" %>

app/views/tools/index.html.erb
<% flash.each do |type, msg| %>
  <h1><%= content_tag :div, msg, class: "flash_#{type}" %></h1>
<% end %>

<h1>All Tools</h1>

<% @tools.each do |tool| %>
  <!-- <p><%= tool.name %>, use: (<%= tool.use %>)</p> -->
  <!-- <p><%= link_to(tool.name, tool_path(tool)) %>, use: <%= tool.use %></p> -->
  <p><%= link_to(tool.name, tool) %>, use: <%= tool.use %></p>
  <p><%= link_to "Edit", edit_tool_path(tool) %></p>
  <p><%= link_to "Delete", tool_path(tool), method: :delete %></p>
<% end %>

<%= link_to("New Tool", new_tool_path) %>

app/views/tools/show.html.erb
<h1><%= @tool.name %></h1>
<p><%= @tool.use %></p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<%= flash[:notice] %>

<h2>Tools:</h2>
<% @user.tools.each do |tool| %>
  <%= tool.name %>
  <%= tool.use %>
<% end %>